### ISSUE TITLE
Utilisation hors ligne possible

### ISSUE THREAD

**Issue by christaus** [erischon/project-mycookbook#3]
Pourquoi ne pas implémenter l'utilisation et la synchro depuis un cache local html5 pour pouvoir utiliser l'application hors ligne tout en conservant la synchro en ligne?

https://developer.mozilla.org/fr/docs/Web/API/Window/localStorage

**Comment by erischon** [comment]
C’est une très bonne idée, merci !

j’ajoute ça à ma longue liste des new features 😇.

Encore merci pour le coup de main,
